### ISSUE TITLE
Accessibility Project

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#321]
### Summary
SDS Accessibility Project Plan for understanding first the work that is needed for the SDS libraries but also an understanding for how the SDS library can help other products become more accessible 

### Intended Outcome
Create a summary of the work that is needed to make the SDS library AA accessibility standard both with design and engineering updates 

### How it will work
We will source data from Github and present visualizations of commit activity under the Activity Tab.

### Tasks
- [ ] Look into accessibility reviews 
- [ ] Design review of SDS 
- [ ] Determine Eng support 

Sub Tickets:
- [x] #390  
- [x] #392 
- [x] #393 
- [x] #394 

[SDS Accessibility Assessment Plan](https://docs.google.com/document/d/1igRbpadtd66WcygdwXtIIOt3puV3Z0q6X0QdCDnWXdo/edit#heading=h.r4uah7cdjnvo )
