### ISSUE TITLE
Complete Outstanding Figma Components

### ISSUE THREAD

**Issue by cathystoli** [chanzuckerberg/sci-components#329]
- [x] Accordion
    - Release notes: #373
    - Zeroheight documentation: #381 
- [x] Slider
    - Release notes: #374
    - Zeroheight documentation: #383 
- [x] Table (for single cell)
    - Release notes: #375
    - Zeroheight documentation: #382 
- [x] Jump-to Navigation
    - Release notes: #378 
    - Zeroheight documentation: #380 

---

### Descoped

- [ ] On-page Navigation
    - Release notes: #377 
    - Zeroheight documentation: #379
