### ISSUE TITLE
Chromatic test for ButtonIcon

### ISSUE THREAD

**Issue by liaprins** [chanzuckerberg/sci-components#453]
### Alignment
- [x] Align with design (and product, other engineers, if necessary) on the visual traits to include as permutation dimensions for the Chromatic test
- Find the component in this doc as a starting point: [Chromatic tests: Which component dimensions to consider looping through](https://docs.google.com/document/d/1i40YV1rX61dNzGsqbhqJAD8PL1puCecX7rnHgD_FawE/edit#)
- Permutation dimensions may include the component’s props, but it may not always be necessary to include every prop
- If the component can be interacted with, or if part of it can (e.g. an “x” button or similar within it), it should include pseudo state as a permutation dimension

- [x] Once the permutation dimensions are aligned on, list them in this issue as checkboxes to track them

### Permutation dimensions to include
- [x] **sdsType**: Primary, Secondary, Tertiary
- [x] **sdsSize**: Large, Medium, Small
- [x] **on**: false, true
- [x] **disabled**: false, true
- [x] **pseudo-state**: default, hover, active, focus

#### Exceptions, notes
- [x] sdsType Primary and Secondary do _not_ have sdsSize Medium
- [x] Secondary x Large and all Tertiary sizes do _not_ have the "on" dimension
- [x] No on/off iteration for primary x small ([UPDATE 05/22/23 PER PR COMMENT BY CONNOR](https://github.com/chanzuckerberg/sci-components/pull/462#issuecomment-1557676343))
- [x] Don't use the same icon throughout; instead, vary the icon to match known usecases in product according to this screenshot:
![Screenshot 2023-05-10 at 11 35 50](https://github.com/chanzuckerberg/sci-components/assets/17435353/b4b7c61a-b00f-40b7-9639-491a54f49cf8)
- [x] Move `disabled=true` (for default pseudo state only) to be visually part of the pseudo-state row, in terms of layout in the UI
- Disabled is not yet needed in product for Tertiary of any size, however, I will still include it in the Chromatic test (and designs do exist for it)
- ButtonIcon uses the default browser focus state

### Tips for writing Chromatic tests
- Write the tests in index.stories.tsx within the component’s folder
- Name the story page LivePreview `export const LivePreview ... `
- Use or create an array per permutation dimension and loop through each to iteratively create all relevant combinations of the component
- Put pseudo-state at the lowest level
- See Button's Live Preview story for an example
- [More about Chromatic](https://storybook.js.org/docs/react/writing-tests/visual-testing#setup-chromatic-addon)
- [More about Storybook's Pseudo State addon](https://storybook.js.org/addons/storybook-addon-pseudo-states)
