### ISSUE TITLE
Chromatic test for Tooltip

### ISSUE THREAD

**Issue by liaprins** [chanzuckerberg/sci-components#461]
### Alignment
- [ ] Align with design (and product, other engineers, if necessary) on the visual traits to include as permutation dimensions for the Chromatic test
- Find the component in this doc as a starting point: [Chromatic tests: Which component dimensions to consider looping through](https://docs.google.com/document/d/1i40YV1rX61dNzGsqbhqJAD8PL1puCecX7rnHgD_FawE/edit#)
- Permutation dimensions may include the component’s props, but it may not always be necessary to include every prop
- If the component can be interacted with, or if part of it can (e.g. an “x” button or similar within it), it should include pseudo state as a permutation dimension

- [ ] Once the permutation dimensions are aligned on, list them in this issue as checkboxes to track them

### Permutation dimensions to include
- [x] **Dimension**: properties

#### Exceptions, notes
- [ ] Add exceptions to combinations here
- ... and any other notes

### Tips for writing Chromatic tests
- Write the tests in index.stories.tsx within the component’s folder
- Name the story page LivePreview `export const LivePreview ... `
- Use or create an array per permutation dimension and loop through each to iteratively create all relevant combinations of the component
- Put pseudo-state at the lowest level
- See Button's Live Preview story for an example
- [More about Chromatic](https://storybook.js.org/docs/react/writing-tests/visual-testing#setup-chromatic-addon)
- [More about Storybook's Pseudo State addon](https://storybook.js.org/addons/storybook-addon-pseudo-states)
