### ISSUE TITLE
Chromatic test for Button

### ISSUE THREAD

**Issue by liaprins** [chanzuckerberg/sci-components#468]
### Alignment
- [x] Align with design (and product, other engineers, if necessary) on the visual traits to include as permutation dimensions for the Chromatic test
- Find the component in this doc as a starting point: [Chromatic tests: Which component dimensions to consider looping through](https://docs.google.com/document/d/1i40YV1rX61dNzGsqbhqJAD8PL1puCecX7rnHgD_FawE/edit#)
- Permutation dimensions may include the component’s props, but it may not always be necessary to include every prop
- If the component can be interacted with, or if part of it can (e.g. an “x” button or similar within it), it should include pseudo state as a permutation dimension

- [x] Once the permutation dimensions are aligned on, list them in this issue as checkboxes to track them

### Permutation dimensions to include
- [x] **sdsStyle**: rounded, square, minimal
- [x] **sdsType**: primary, secondary
- [x] **icon**: false, true
- [x] **disabled**: false, true
- [x] **pseudo-state**: default, hover, active, focus-visible

#### Exceptions, notes
- [x] `sdsStyle=minimal` x `sdsType=secondary` Buttons cannot have icons
- [x] The only relevant pseudo-state for `disabled=true` is default; put this in the same row as the other pseudo-state iterations, visually
- [x] Maintain the original LivePreview test, name this new one ScreenshotTest

Here's a rough sketch of the general layout I plan to use for the Screenshot Test page:
![Button Chromatic test layout](https://github.com/chanzuckerberg/sci-components/assets/17435353/7df19fbc-ce49-4734-877a-cd5774e84ddc)

### Tips for writing Chromatic tests
- Write the tests in index.stories.tsx within the component’s folder
- Name the story page LivePreview `export const LivePreview ... `
- Use or create an array per permutation dimension and loop through each to iteratively create all relevant combinations of the component
- Put pseudo-state at the lowest level
- See Button's Live Preview story for an example
- [More about Chromatic](https://storybook.js.org/docs/react/writing-tests/visual-testing#setup-chromatic-addon)
- [More about Storybook's Pseudo State addon](https://storybook.js.org/addons/storybook-addon-pseudo-states)

**Comment by liaprins** [comment]
Closed via #463
